### PR TITLE
Add a Catppuccin example

### PR DESCRIPTION
**Pull request by gs-101**
This pull request adds an example using [Catppucchin](url)'s mocha color palette to the [customizable colors](https://github.com/alphapapa/prism.el?tab=readme-ov-file#customizable-colors) header.

The font used in the screenshot is [CaskaydiaCove Nerd Font](https://www.programmingfonts.org/#cascadia-code).

The colors were picked based on the colors used in the theme's Org headings, and I just took `:lightens` and `:desaturations` from one of the other examples.

catppuccin-mocha

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Gabriel,

Thanks, but the current readme has probably too many screenshots already, and this new one is only slightly different than [this screenshot](https://github.com/alphapapa/prism.el/raw/master/images/doom-spacegrey.png).  I don't want to clutter the readme any more than it already is.

If you'd like, this would be a suitable contribution to a wiki on this repository instead.  Would you be interested in contributing this to one?

**Comment by gs-101** [comment]
> and this new one is only slightly different than [...]

Are you referring to the colorscheme? If yes, then I thought about adding the Catppuccin screenshot to let user know about `catppuccin-get-color`.
If you're refering to the formating, I can change that just fine, since this sceenshot isn't from my config, but I don't know how you got the **bold** and <ins>underlined</ins> on your code.
If you mean the font, I don't know the font you used for your screenshots, but I would change it for mine so it stays consistent.

> this would be a suitable contribution to a wiki on this repository instead.

Thanks, I never contributed to Github wiki before, but I will look into that.

**Comment by alphapapa** [comment]
Showing how to use `catppucin-get-color` would best be demonstrated in textual source code, e.g. on the wiki.  I made a page for you to add your example: https://github.com/alphapapa/prism.el/wiki/integrating-with-custom-themes

**Comment by gs-101** [comment]
[Here](https://github.com/gs-101/catppuccin-example/wiki) is what I wrote on my fork, feel free to suggest any changes.

**Comment by alphapapa** [comment]
I changed the wiki permission so you can add your content now.

**Comment by gs-101** [comment]
Done, I also changed the page's edit mode to Org.

**Comment by alphapapa** [comment]
Thanks.

**Pull request closed without merging**
